# Generated by Django 5.2.17 on 2026-08-22 19:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_add_bitunix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='api_key',
            field=models.CharField(blank=True, help_text='Öffentlicher Börsenschlüssel. Für Paper-Trading nicht erforderlich.', max_length=120, null=True, verbose_name='API-Key (optional)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='countdown',
            field=models.IntegerField(default=1, help_text='Wartezeit nach Bot-Start in Minuten, in der Kurse gesammelt aber noch keine Käufe ausgeführt werden.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Start-Countdown (Minuten)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='countdown_reset_indicators',
            field=models.BooleanField(default=False, help_text='Indikatoren und 10-Punkte-Preisbuffer nach einem Verkauf zurücksetzen.', verbose_name='Indikatoren nach Verkauf zurücksetzen'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='deltadelta_threshold_buy',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Kaufschwelle für das geglättete Zwei-Punkt-Momentum ((NDA + vorherige NDA) / 2). Im Backtesting als „DeltaDelta“ einstellbar.', max_digits=20, verbose_name='DeltaDelta (geglättetes Momentum) – Kaufschwelle'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='div_DVA_prev_NDA_threshold_buy',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Kaufschwelle für die relative Momentum-Beschleunigung (DVA / vorherige NDA). Im Backtesting als „Beschleunigung“ einstellbar.', max_digits=20, verbose_name='Beschleunigung (DVA / prev NDA) – Kaufschwelle'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='exchange',
            field=models.CharField(choices=[('binance', 'Binance'), ('bingx', 'BingX'), ('bybit', 'Bybit'), ('bitmart', 'BitMart'), ('bitunix', 'Bitunix')], default='binance', help_text='Kryptobörse für Marktdaten und Paper-Trading: Binance, BingX, Bybit, BitMart oder Bitunix.', max_length=20, verbose_name='Börse (Exchange)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), help_text='Simulierte Handelsgebühr je Kauf und Verkauf in Prozent.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Handelsgebühr je Order (%)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Bot aktuell laufen soll.', verbose_name='Bot läuft'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='market',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='spot', help_text='Handelsmarkt: Spot (Kassamarkt) oder Futures (Derivate/Swaps).', max_length=20, verbose_name='Marktart'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(help_text='Frei wählbare Bezeichnung (mindestens 3 Zeichen), z. B. „Binance Spot Top 5“.', max_length=100, verbose_name='Name der Konfiguration'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='nda_threshold_buy',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Kaufschwelle für die prozentuale Preisänderung zum Vorpreis (((P0 - P1) / P1) * 100). Im Backtesting als „NDA“ einstellbar.', max_digits=20, verbose_name='NDA (normalisierte Preisänderung) – Kaufschwelle'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sales_stop_threshold',
            field=models.FloatField(default=0.0, help_text='Maximaler Verlust des Gesamtkapitals in Prozent (0 = deaktiviert).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gesamtverlustgrenze / Sales Stop (%)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Geheimer Börsenschlüssel. Für Paper-Trading nicht erforderlich.', max_length=120, null=True, verbose_name='Secret-Key (optional)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='start_capital',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), help_text='Virtuelles Anfangskapital für die Paper-Trading-Simulation.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Startkapital (USDT)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='stop_loss',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Prozentualer Kursverlust ab Einstieg zum automatischen Verkauf.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Stop Loss (%)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='symbols',
            field=models.CharField(default='BTC/USDT,ETH/USDT,SOL/USDT,LTC/USDT,XRP/USDT', help_text='Kommagetrennte CCXT-Symbole (z. B. BTC/USDT, ETH/USDT).', max_length=200, verbose_name='Handelspaare (Symbole)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='take_profit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Prozentualer Kursgewinn ab Einstieg zum automatischen Verkauf.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Take Profit (%)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='time_interval',
            field=models.IntegerField(default=2, help_text='Pause zwischen zwei Preisprüfzyklen in Sekunden (1–300 s).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Auswertungsintervall (Sekunden)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='trade_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('10'), help_text='Virtueller Nominalbetrag je Position. Kaufgebühr muss zusätzlich gedeckt sein.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Trade-Betrag pro Position (USDT)'),
        ),
    ]
