# Generated by Django 5.2.17 on 2026-08-23 18:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Futures-Hebel je Konfiguration und Long-/Short-Richtung im Handelsjournal.

    Alle Felder sind mit rückwärtskompatiblen Standardwerten belegt
    (Hebel 1, Richtung „long“), damit bestehende Konfigurationen und
    historische TradingLogs ihr bisheriges Verhalten exakt beibehalten.
    """


    dependencies = [
        ('trading', '0012_alter_configuration_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='leverage',
            field=models.PositiveIntegerField(default=1, help_text='Hebel für den Futures-Markt. 1 = ohne Hebel. Der Wert wird zusätzlich auf den je Börse konfigurierten Maximalhebel begrenzt; im Spot-Markt wird immer ohne Hebel gerechnet.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)], verbose_name='Hebel (nur Futures)'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='trade_direction',
            field=models.CharField(choices=[('long', 'Nur Long (Kauf)'), ('short', 'Nur Short (Leerverkauf)'), ('both', 'Long und Short')], default='long', help_text='Long (steigende Kurse), Short (fallende Kurse) oder beide Richtungen. Short ist ausschließlich im Futures-Markt möglich.', max_length=10, verbose_name='Handelsrichtung'),
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='direction',
            field=models.CharField(default='long', max_length=10),
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tradinglog',
            name='margin',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
    ]
