# Generated by Django 5.2.17 on 2026-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_configuration_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='configuration',
            name='has_live_credentials',
            field=models.BooleanField(
                default=False,
                help_text='Gibt an, ob Live-API-Schluessel konfiguriert wurden. Die Schluessel selbst werden als Umgebungsvariablen beim Container-Start uebergeben und nie in der Datenbank gespeichert.',
                verbose_name='Echtzeit-Handel aktiviert',
            ),
        ),
    ]
