# Generated by Django 5.2.17 on 2026-09-07 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0013_remove_configuration_api_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="leverage",
            field=models.IntegerField(
                default=1,
                help_text="Hebelwirkung für Futures-Handel (1 = kein Hebel, >= 1).",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hebel (Leverage)",
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="trade_direction",
            field=models.CharField(
                default="long",
                help_text="Richtrichtung des Handels: long (Kauf) oder short (Verkauf).",
                max_length=10,
                verbose_name="Richtrichtung",
            ),
        ),
    ]
