# Generated by Django 5.2.17 on 2026-09-09 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_configuration_leverage_trade_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='leverage',
            field=models.IntegerField(default=1, help_text='Hebelwirkung für Futures-Handel (1 = kein Hebel). Achtung: Die Engine bildet derzeit ausschließlich Spot-Trades ohne Hebel; der Wert wird nur aufgezeichnet.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hebel (Leverage)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='trade_direction',
            field=models.CharField(choices=[('long', 'Long (Kaufen)'), ('short', 'Short (Verkauf) [nicht implementiert]')], default='long', help_text='Handelsrichtung. Achtung: Der Bot handelt derzeit ausschließlich long; „short“ wird nur gespeichert und hat keine Auswirkung auf die Strategie.', max_length=10, verbose_name='Richtung'),
        ),
    ]
