#!/usr/bin/env python3
"""Benchmark local hardware and write an optimized Docker Compose env profile."""

from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.local_hardware import detect_hardware, recommend_profile


def read_env(path):
    values = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def build_environment(profile, existing):
    generated = {
        "SECRET_KEY": existing.get("SECRET_KEY") or secrets.token_urlsafe(48),
        "PASSPHRASE": existing.get("PASSPHRASE") or secrets.token_urlsafe(32),
        "PASSPHRASE_GATE_ENABLED": existing.get("PASSPHRASE_GATE_ENABLED", "True"),
        "AUTOSTART_BOTS": existing.get("AUTOSTART_BOTS", "True"),
        "POSTGRES_DB": existing.get("POSTGRES_DB", "tbot"),
        "POSTGRES_USER": existing.get("POSTGRES_USER", "tbot"),
        "POSTGRES_PASSWORD": existing.get("POSTGRES_PASSWORD") or secrets.token_urlsafe(24),
        "WEB_PORT": existing.get("WEB_PORT", "8369"),
        "CELERY_LOG_LEVEL": existing.get("CELERY_LOG_LEVEL", "INFO"),
    }
    generated.update(profile.env())
    return generated


def write_env(path, values, hardware):
    lines = [
        "# Generated by scripts/tune_local_hardware.py",
        f"# architecture={hardware.architecture} cpus={hardware.cpu_count} ",
        f"# memory_mb={hardware.memory_mb} disk_free_mb={hardware.disk_free_mb}",
        f"# cpu_score={hardware.cpu_score} hashes_per_second disk_write_mbps={hardware.disk_write_mbps}",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as output:
        os.fchmod(output.fileno(), 0o600)
        output.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=".env.local")
    parser.add_argument("--render-free-simulation", action="store_true")
    parser.add_argument("--no-benchmark", action="store_true")
    parser.add_argument("--print-only", action="store_true")
    args = parser.parse_args()

    output = Path(args.output)
    hardware = detect_hardware(run_benchmarks=not args.no_benchmark)
    profile = recommend_profile(hardware, simulate_render_free=args.render_free_simulation)
    values = build_environment(profile, read_env(output))
    report = {
        "hardware": hardware.__dict__,
        "profile": profile.env(),
        "output": str(output),
    }
    print(json.dumps(report, indent=2))
    if not args.print_only:
        write_env(output, values, hardware)
        print(f"Wrote optimized profile to {output} (mode 0600).")


if __name__ == "__main__":
    main()
